name: Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: Release Tag
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Install, build, check and test
      run: |
        npm install
        npm run build
        cd docs/samples
        npm install
        cd ../..
        npm run build-web
        npm run test-imports
        npm pack
        sudo apt-get install zip
        cd dist/browser
        zip -r ../../con-reg-exp-browser.zip *
    - name: Release
      uses: softprops/action-gh-release@v1
      if: "${{ github.event.inputs.tag_name != '' }}"
      with:
        files: |
          ./con-reg-exp-*.tgz
          ./con-reg-exp-*.zip
        draft: false
        tag_name: ${{ github.event.inputs.tag_name }}
        fail_on_unmatched_files: true
        generate_release_notes: true
    - name: NPM Publish
      if: "${{ github.event.inputs.tag_name != '' }}"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm publish
    - name: Prepare an Artifact
      run: |
        cd web
        zip -r ../web.zip *
    - name: Upload an Artifact
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: |
          ./*.zip
          ./*.gz
          ./*.tgz
